name: CI

on:
  - pull_request
  - push

jobs:
  build:
    name: PHP ${{ matrix.php-version }}_${{ matrix.stability }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1', '8.2']
        stability: [lowest, stable]
        include:
          - php-version: '8.3'
            stability: stable
            flags: "--ignore-platform-req=php"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-${{ matrix.stability }} --no-interaction --no-progress ${{ matrix.flags }}
      - name: Execute tests
        run: ./vendor/bin/phpunit

  PHPUnit-Dev:
    name: PHPUnit (dev)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          # 1. friendsofphp/php-cs-fixer v3.10.0 requires sebastian/diff ^4.0, but phpunit/phpunit dev-main requires
          # sebastian/diff ^5.0
          # 2. --with-all-dependencies phpunit/phpunit dev-main requires phpunit/php-code-coverage ^10.0 -> found
          # phpunit/php-code-coverage[dev-main, 10.0.x-dev (alias of dev-main)] but the package is fixed to 9.2.16
          command: |
            composer remove realodix/relax --dev
            composer require phpunit/phpunit dev-main --with-all-dependencies
      - name: Execute tests
        run: ./vendor/bin/phpunit --migrate-configuration
